### ISSUE TITLE
Last update don't work 

### ISSUE THREAD

**Issue by LexRotor** [oae/gnome-shell-extensions-sync#39]
Hi, the lastest update doest not work on fedora 34 gnome 40:

Error: Invalid type [object GjsGlobal]

**Comment by KlausEverWalkingDev** [comment]
> Went back to gnome-shell-extensions-sync (Gnome 40, version 14) worked until the issue is fixed.

How did you do the downgrade?

**Comment by kev005** [comment]
I downloaded the zip file of the previous version from https://extensions.gnome.org/extension/1486/extensions-sync/ and copied the contents into my local extensions folder in a new empty extensions-sync@elhan.io directory.

$HOME/.local/share/gnome-shell/extensions/extensions-sync@elhan.io

Not really a good solution because the Gnome extensions updater will just grab the new version the next time you login.

**Comment by oae** [comment]
The latest release(v16) should fix it. Thanks for the report.
